
#configuration a la base de donnée en developpement
spring.datasource.url=jdbc:mysql://localhost:3306/isepat_dev
spring.datasource.username=root
spring.datasource.password=

#mettre a jour la structure sans jamais effacer les donnée presente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cle secrete utilisee pour signer les tokens JWT (fixe, ne change pas au redemarrage)
jwt.secret=IsepAtGestionEtudiantSecretKeyPourSignerLesTokensJWT2026